# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Featured Notebooks
    url: /#notebooks
    weight: 11
  - name: Recent Projects
    url: /#news
    weight: 12
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  # - name: Courses
  #   url: courses/
  #   weight: 40
